---

- name: Run the cache service
  docker_container:
    name: cache
    image: redis:5
    pull: yes
    hostname: cache
    restart_policy: always
    networks:
      - name: openzaak
    purge_networks: yes
    networks_cli_compatible: yes

- name: Run the OpenZaak backend service
  docker_container:
    name: "{{ item.name }}"
    image: openzaak/open-zaak:latest
    pull: yes
    hostname: "{{ item.name }}"
    restart_policy: always
    networks:
      - name: openzaak
    purge_networks: yes
    networks_cli_compatible: yes
    volumes:
      - /var/run/postgresql:/var/run/postgresql
      - openzaak-private-media:/app/private-media
    ports:
      - "127.0.0.1:{{ item.port }}:8000"
    env_file: /home/openzaak/.env
  with_items: "{{ openzaak_replicas }}"
