version: '3.4'

services:
  openzaak-alfresco-share:
    image: openzaak/alfresco-share:1.0-SNAPSHOT
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: openzaak-alfresco-acs
      REPO_PORT: 8080
    ports:
      - "11230:8080"
      - "11231:8888"

  openzaak-alfresco-acs:
    image: openzaak/alfresco-content-services:1.0-SNAPSHOT
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "11232:8080"
      - "11233:8888"
    volumes:
      - openzaak-alfresco-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - openzaak-alfresco-postgres

  openzaak-alfresco-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "11234:5432"
    volumes:
      - openzaak-alfresco-db-volume:/var/lib/postgresql/data

  openzaak-alfresco-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: openzaak-alfresco-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: openzaak-alfresco-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - openzaak-alfresco-ass-volume:/opt/alfresco-search-services/contentstore
      - openzaak-alfresco-ass-volume:/opt/alfresco-search-services/data
volumes:
  openzaak-alfresco-acs-volume:
  openzaak-alfresco-db-volume:
  openzaak-alfresco-ass-volume:
