apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-zaak.fullname" . }}
  labels:
    {{- include "open-zaak.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.settings.secretKey | toString | b64enc | quote }}
  DB_PASSWORD: {{ .Values.settings.database.password | toString | b64enc | quote }}
  {{- if .Values.settings.sentry.dsn }}
  SENTRY_DSN: {{ .Values.settings.sentry.dsn | toString | b64enc | quote }}
  {{- end }}
  {{- if .Values.settings.email.password }}
  EMAIL_PASSWORD: {{ .Values.settings.email.password | toString | b64enc | quote }}
  {{- end }}
