---

openzaak_domain: "{{ inventory_hostname }}"

openzaak_db_port: 5432
openzaak_db_host: /var/run/postgresql
openzaak_db_name: openzaak
openzaak_db_username: openzaak
openzaak_db_password: openzaak

openzaak_ssl: "{{ certbot_create_if_missing | default(yes) | bool }}"

openzaak_secret_key: override-me
openzaak_env_file: /home/openzaak/.env

openzaak_version: latest
openzaak_replicas:
  - name: openzaak-0
    port: 8000
  - name: openzaak-1
    port: 8001
  - name: openzaak-2
    port: 8002
