---

- name: Deploy the Open Zaak apps in the cluster
  hosts: localhost

  vars_files:
    - vars/db_credentials.yml
    - vars/open-zaak.yml
    - vars/open-notificaties.yml
    # - vars/nlx.yml

  collections:
    - openzaak.deploy

  roles:
    - role: open_zaak_k8s
      vars:  # these override vars_files
        openzaak_version: '1.1.0'
        openzaak_db_host: "{{ db.privateIp }}"
        openzaak_db_port: "{{ db.port }}"
      tags:
        - openzaak

    - role: open_notificaties_k8s
      vars:
        opennotificaties_db_host: "{{ db.privateIp }}"
        opennotificaties_db_port: "{{ db.port }}"
      tags:
        - opennotificaties
