---

- name: Install postgis extension
  package:
    name:
      - postgis

- name: Enable the required database extensions
  postgresql_ext:
    name: "{{ item }}"
    db: openzaak
    state: present
    port: "{{ database_port | default(5432) }}"
  become: yes
  become_user: postgres
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
  with_items:
    - postgis
    - pg_trgm
