name: Code quality checks

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yml'
  pull_request:
    paths:
      - '**.py'
      - '**.yml'
  workflow_dispatch:

jobs:
  open-api-workflow-code-quality:
    uses: maykinmedia/open-api-workflows/.github/workflows/code-quality.yml@6fc8ab4e220340d41326e504aaf476e4074d0ec6
    with:
      python-version: '3.11'
      node-version: '18'
      apt-packages: 'libgdal-dev gdal-bin'

      isort-src-pattern: 'src'
      black-src-pattern: 'src docs'
      flake8-src-pattern: 'src'

      django-settings-module: 'openzaak.conf.ci'
      django-secret-key: dummy

  # openzaak specific
  spdx:
    name: SPDX header check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: maykinmedia/setup-django-backend@v1.3
        with:
          python-version: '3.11'
          setup-node: false
      - name: Run check
        run: ./bin/check_spdx.py src
