name: Publish forked Open Zaak image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag to build and push
        required: true
        default: latest-utrecht

env:
  IMAGE_NAME: scrumteamzgw/open-zaak

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and push Docker image

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build \
            --tag $IMAGE_NAME:${{ github.event.inputs.tag }} \
            --build-arg COMMIT_HASH=${GITHUB_SHA} \
            --build-arg RELEASE=${{ github.event.inputs.tag }} \
          .
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push the Docker image
        run: docker push $IMAGE_NAME:${{ github.event.inputs.tag }}
